name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore TownSuite.Web.SSV3Facade.sln
    - name: Build
      run: dotnet build -c Release TownSuite.Web.SSV3Facade.sln --no-restore
    - name: Test
      run: dotnet test TownSuite.Web.SSV3Facade.sln --no-build --verbosity normal
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nuget-packages
        path: |
          TownSuite.Web.SSV3Facade.Interfaces/bin/Release/*.nupkg
          TownSuite.Web.SSV3Facade.Prometheus/bin/Release/*.nupkg
          TownSuite.Web.SSV3Facade/bin/Release/*.nupkg
        retention-days: 1
