name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore TownSuite.Web.SSV3Adapter.sln
    - name: Build
      run: dotnet build -c Release TownSuite.Web.SSV3Adapter.sln --no-restore
    - name: Test
      run: dotnet test TownSuite.Web.SSV3Adapter.sln --verbosity normal
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nuget-packages
        path: |
          TownSuite.Web.SSV3Adapter.Interfaces/bin/Release/*.nupkg
          TownSuite.Web.SSV3Adapter.Prometheus/bin/Release/*.nupkg
          TownSuite.Web.SSV3Adapter/bin/Release/*.nupkg
        retention-days: 1
    - name: Generate XML SBOM
      uses: CycloneDX/gh-dotnet-generate-sbom@v1
      with:
        path: ./TownSuite.Web.SSV3Adapter.sln
  
